### ISSUE TITLE
"eslint-config-prettier" upgrade to v8.x breaks with with dependency to linz/style-js

### ISSUE THREAD

**Issue by SchlauFuchs** [linz/style-js#162]
Error: Cannot read config file: C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\eslint-config-prettier\@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\.eslintrc.js
    at Object.<anonymous> (C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\eslint-config-prettier\@typescript-eslint.js:1:69)
    at Module._compile (C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at module.exports (C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\@eslint\eslintrc\node_modules\import-fresh\index.js:32:59)
    at loadJSConfigFile (C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\@eslint\eslintrc\lib\config-array-factory.js:225:16)
    at loadConfigFile (C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\@eslint\eslintrc\lib\config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web\node_modules\@eslint\eslintrc\lib\config-array-factory.js:609:42)
npm ERR! code 2
npm ERR! path C:\Users\KHackemesser\code\landonline-auth-service\example-client-app\web

**Comment by blacha** [comment]
Looks like this was resolved.
